import Footer from "./footer";
import Header from "./header";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<div className="min-h-screen bg-primary">
			<Header />
			{/* <Navbar /> */}
			<main>{children}</main>
			<Footer />
		</div>
	);
}
