// These styles apply to every route in the application

// import Navbar from './navbar';
// import Footer from './footer';
import '../../styles/globals.css';
import Header from './header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {/* <Navbar /> */}
      <main>{children}</main>
      {/* <Footer /> */}
    </>
  );
}
