// These styles apply to every route in the application

// import Navbar from './navbar';
// import Footer from './footer';
// import '@/styles/globals.css';
import Footer from "./footer";
import Header from "./header";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<Header />
			{/* <Navbar /> */}
			<main>{children}</main>
			{/* TODO: 푸터 추가해야함 현재 추가시 컨텐츠가 없어서 중간에 위치하기 때문에 일단 보류 */}
			<Footer />
		</>
	);
}
